import os

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
API_URL = os.getenv("API_URL")
API_KEY = os.getenv("API_KEY")
COURSE_LINK = os.getenv("COURSE_LINK")
USDT_WALLET_ADDRESS = os.getenv("USDT_WALLET_ADDRESS")
BANK_ACCOUNT_DETAILS = os.getenv("BANK_ACCOUNT_DETAILS")
